name: CI for HelloWorld

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: mst619/HelloWorldDemo
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: 3thannn/DevOpsQA
        path: tests
        token: ${{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}}
        
    - name: Begin Pytest
      run: |
        mv ./tests/*.* ./
        pytest --cov
        
